// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGcDiMyv6Hv7t3j6M1Bth1KWjJosquxjY',
    appId: '1:791338295448:web:0392677ad51add4b59f0ed',
    messagingSenderId: '791338295448',
    projectId: 'one-app-todo',
    authDomain: 'one-app-todo.firebaseapp.com',
    storageBucket: 'one-app-todo.firebasestorage.app',
    measurementId: 'G-SZVMB7YTSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZ5dsRNTA8wEnepttMy5wj0vCPlistV4',
    appId: '1:791338295448:android:ff99b83c97f5d44759f0ed',
    messagingSenderId: '791338295448',
    projectId: 'one-app-todo',
    storageBucket: 'one-app-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsYQciAcChXSzqxuhh8RZNUVRD76hSTqA',
    appId: '1:791338295448:ios:0f7a4d152ef4dd5059f0ed',
    messagingSenderId: '791338295448',
    projectId: 'one-app-todo',
    storageBucket: 'one-app-todo.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsYQciAcChXSzqxuhh8RZNUVRD76hSTqA',
    appId: '1:791338295448:ios:0f7a4d152ef4dd5059f0ed',
    messagingSenderId: '791338295448',
    projectId: 'one-app-todo',
    storageBucket: 'one-app-todo.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGcDiMyv6Hv7t3j6M1Bth1KWjJosquxjY',
    appId: '1:791338295448:web:b2bd4a88919ca6db59f0ed',
    messagingSenderId: '791338295448',
    projectId: 'one-app-todo',
    authDomain: 'one-app-todo.firebaseapp.com',
    storageBucket: 'one-app-todo.firebasestorage.app',
    measurementId: 'G-7964EVV8C9',
  );
}
